name: Models Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/models
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"
      - name: Set up Kaggle API token
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_API_TOKEN }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Create models from checkpoint files
        run: python src/al_bab/test_loader.py
      - name: Run unit tests
        run: pytest tests/
