name: Models Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"
      - name: Install dependencies
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[other]"
      - name: Get Test Data
        run: python src/al_bab/data/test_loader.py
      - name: Run unit tests
        run: pytest tests/
